plugins {
    id 'idea'
    id 'maven-publish'
    alias libs.plugins.loom
}

def javaVersion = 21

group = maven_group_id

def ENV = System.getenv()
def NOW = new Date()
def buildTime = ENV.BUILD_TIME ?: NOW.format('yyyyMMddHHmmss')

boolean isPreviewBuild = !ENV.TAG || ENV.TAG.matches(".+-.+")
def buildNumber = !ENV.TAG ? ("${ENV.BUILD_NUMBER ? "build.${ENV.BUILD_NUMBER}" : buildTime}") : ""
version = (ENV.TAG ?: "${libs.versions.minecraft.get()}-development") + ((isPreviewBuild && !ENV.TAG) ? "+${buildNumber}" : "")

println("Building ${project.name} ${version}")

repositories {
    mavenCentral()

    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org"
        content {
            includeGroupAndSubgroups "org.parchmentmc"
        }
    }

    maven {
        name = "QuiltMC"
        url = "https://maven.quiltmc.org/repository/release"

        content {
            includeGroupAndSubgroups("org.quiltmc")
        }
    }

    maven {
        name = "Up-Mods"
        url = "https://maven.uuid.gg/releases"
    }

    maven {
        name = "Ladysnake"
        url = "https://maven.ladysnake.org/releases"
    }

    maven {
        name = "Ladysnake (snapshots)"
        url = "https://maven.ladysnake.org/snapshots"
    }

    maven {
        name = "TeamResourceful"
        url = "https://maven.teamresourceful.com/repository/maven-releases"
    }

    maven {
        name = "JourneyMap"
        url = "https://jm.gserv.me/repository/maven-public"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases"
    }

    maven {
        name = "Shedaniel"
        url = "https://maven.shedaniel.me"
    }

    maven {
        name = "TheIllusiveC4"
        url = "https://maven.theillusivec4.top"
    }

    maven {
        name = "Masa"
        url = "https://masa.dy.fi/maven"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "CurseMaven"
                url = "https://www.cursemaven.com"
            }
        }

        filter {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    minecraft libs.minecraft
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    })

    modImplementation libs.fabric.loader
    modImplementation(libs.fabric.api) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }

    compileOnly libs.jetbrains.annotations

    modImplementation libs.bundles.icarus

    modImplementation libs.bundles.origins

    modCompileOnly libs.modmenu
    modLocalRuntime libs.modmenu

    modLocalRuntime libs.emi
}

base {
    archivesName = "${project.name}-Fabric"
}

loom {
    mods {
        "${mod_id}" {
            // Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
            sourceSet("main")
        }
    }
    mixin {
        useLegacyMixinAp = false
    }

    runs {
        configureEach {
            it.property('mixin.debug', 'true')
        }

        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")

            if (rootProject.hasProperty('mc_uuid')) {
                programArgs("--uuid", rootProject.mc_uuid)
            }

            if (rootProject.hasProperty('mc_username')) {
                programArgs("--username", rootProject.mc_username)
            }

            if (rootProject.hasProperty('mc_java_agent_path')) {
                vmArg("-javaagent:${rootProject.mc_java_agent_path}")
            }
        }

        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run/server")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
    withSourcesJar()
//        withJavadocJar()
}

javadoc {
    options.tags = ["reason"]
}

jar {
    from(project.file("LICENSE.md")) {
        rename "LICENSE.md", "LICENSE_${mod_id}.md"
    }
    manifest {
        attributes([
                'Specification-Title'     : project.name,
                'Specification-Version'   : project.version,
                'Implementation-Title'    : "${project.name}-Fabric",
                'Maven-Artifact'          : "${maven_group_id}:${project.name}-Fabric:${project.version}",
                'Implementation-Version'  : project.version,
                'Implementation-Timestamp': NOW.format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Timestamp'               : NOW.toInstant().toEpochMilli(),
                'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                'Built-On-Minecraft'      : libs.versions.minecraft.get()
        ])
    }
}

sourcesJar {
    from(project.file("LICENSE.md")) {
        rename "LICENSE.md", "LICENSE_${mod_id}.md"
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(javaVersion)
}

processResources {
    filteringCharset "UTF-8"

    def expandProps = [
            "version"              : version,
            "maven_group_id"       : maven_group_id,
            "mod_id"               : mod_id,
            "mod_display_name"     : mod_display_name,
            "mod_description"      : mod_description,
            "sources_url"          : sources_url,
            "issues_url"           : issues_url,
            "license_url"          : license_url,
            "discord_url"          : discord_url,
            "homepage_url"         : homepage_url,
            "minecraft_version"    : libs.versions.minecraft.get(),
            "curseforge_id"        : curseforge_id,
            "modrinth_id"          : modrinth_id,

            "java_version"         : javaVersion,
            "fabric_loader_version": libs.versions.fabric.loader.get(),
    ]

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishing {
    publications {
        "mavenJava${project.name}"(MavenPublication) {
            artifactId "${rootProject.name}-Fabric"
            from components.java
        }
    }

    repositories {
        if (ENV.MAVEN_UPLOAD_URL) {
            maven {
                url = ENV.MAVEN_UPLOAD_URL
                credentials {
                    username = ENV.MAVEN_UPLOAD_USERNAME
                    password = ENV.MAVEN_UPLOAD_PASSWORD
                }
            }
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
