[versions]
forge = "47.1.3"

curios = "5.9.0+1.20.1"
caelus = "3.2.0+1.20.1"

origins = "1.20.1-1.10.0.9"
apoli = "1.20.1-2.9.0.8"
calio = "1.20.1-1.11.0.5"

[libraries]
curios = { module = "top.theillusivec4.curios:curios-forge", version.ref = "curios" }

caelus = { module = "top.theillusivec4.caelus:caelus-forge", version.ref = "caelus" }

origins = { module = "io.github.edwinmindcraft:origins-forge", version.ref = "origins" }
apoli = { module = "io.github.edwinmindcraft:apoli-forge", version.ref = "apoli" }
calio = { module = "io.github.edwinmindcraft:calio-forge", version.ref = "calio" }

[bundles]
origins = ["origins", "apoli", "calio"]
