plugins {
    alias(libs.plugins.architectury.loom)
}

dependencies {
    minecraft libs.minecraft
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    })

    modImplementation(libs.bundles.origins.fabric) {
        transitive = false
    }
}

afterEvaluate {
    configurations.each {
        println("Configuration: ${it.name}")
    }
}
