name: Build Status

on:
  push:
    branches: [ '*' ]
  pull_request:

env:
  JAVA_VERSION: 21
  GRADLE_BUILD_CACHE_USER: ${{ secrets.GRADLE_BUILD_CACHE_USER }}
  GRADLE_BUILD_CACHE_TOKEN: ${{ secrets.GRADLE_BUILD_CACHE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --rerun-tasks
      - name: Upload build artifacts (Fabric)
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
          path: |
            build/libs/*.jar
            !build/libs/*-dev.jar
